name: cdc-covid-19_env
channels:
  - conda-forge  # Ensure conda-forge has priority
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - statsmodels
  - matplotlib
  - jupyter
  - jupyterlab
  - notebook
  - ipython
  - ipykernel
  - tornado
  - typing-extensions
  - pip:
      - pmdarima  # Ensure pmdarima is installed via pip
